CREATE TABLE members(
    member_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    member_id VARCHAR2(50) UNIQUE,      -- 아이디
    member_pw VARCHAR2(200) NOT NULL,   -- 비밀번호
    member_name VARCHAR2(50) NOT NULL,  -- 실명
    member_addr VARCHAR2(150) NOT NULL, -- 주소
    member_email VARCHAR2(150) UNIQUE,  -- 이메일
    member_phone VARCHAR2(100) UNIQUE,  -- 핸드폰
    member_status NUMBER,               -- 1이면 관리자 0이면 일반회원
    member_nickname VARCHAR2(20),		-- 닉네임
    member_birth VARCHAR2(20)			-- 생년월일    
);

CREATE TABLE newbook(
    newbook_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    newbook_title VARCHAR2(100) NOT NULL,
    newbook_content VARCHAR2(200) NOT NULL,
    newbook_author VARCHAR2(100) NOT NULL,
    newbook_publisher VARCHAR2(50) NOT NULL,
    newbook_count NUMBER CONSTRAINT chk_newbook_count CHECK (newbook_count >= 0),
    newbook_img VARCHAR2(200),
    newbook_category VARCHAR2(50),
    newbook_price NUMBER,
    newbook_isbn VARCHAR2(100),
    newbook_page NUMBER,
    newbook_publication_date DATE
);


CREATE TABLE tradebook(
    tradebook_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,  -- 교환 책 번호 (기본키)
    tradebook_title VARCHAR2(100) NOT NULL,                                   -- 책 제목 (필수 입력)
    member_num NUMBER NOT NULL,                                               -- 회원 번호
    tradebook_condition VARCHAR2(200) NOT NULL,                               -- 교환 원하는 책 (소설, 에세이, 자기계발서 (상태 무관) 이런느낌
    tradebook_content VARCHAR2(200) NOT NULL,                                 -- 교환 내용 정말 재미있게 읽었던 책입니다! 상상력이 풍부하고 따뜻한 이야기라 많은 분들이 읽어보셨으면 좋겠어요. 책 상태도 매우 깨끗하니 안심하고 교환하세요.
    tradebook_status VARCHAR2(200) NOT NULL,                                  -- 책 상태 (필수 입력)
    tradebook_author VARCHAR2(100) NOT NULL,                                  -- 저자 (필수 입력)
    tradebook_trade VARCHAR2(2) DEFAULT 'y',                                  -- 교환 가능 여부 ('y'/'n', 기본값 'y')
    tradebook_method VARCHAR2(120),                                           -- 교환 방식 (직거래/택배)
    tradebook_time VARCHAR2(120),                                             -- 교환 가능 시간 직접입력 오후/오전 언제든 상관없은 이런식
    tradebook_img VARCHAR2(200),                                              -- 책 이미지
    tradebook_isbn VARCHAR2(100),     
    tradebook_location VARCHAR2(100)                                           -- 교환희망지역
);


CREATE TABLE payments (
    payment_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 결제 번호 (기본키)
    member_num NUMBER NOT NULL,                                               -- 결제한 회원 번호
    member_name VARCHAT2(60),
    member_phone VARCHAT2(60),
    member_addr VARCHAR2(150),
    payment_content CLOB,
    newbook_num NUMBER NOT NULL,                                              -- 구매한 책 번호
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                         -- 결제 날짜 (기본값: 현재 시간)
    payment_quantity NUMBER NOT NULL,                                         -- 구매 수량 (필수 입력)
    payment_total_price NUMBER NOT NULL,                                       -- 총 결제 금액 (필수 입력)
    item_status VARCHAR2(20) DEFAULT '배송준비중'
);


CREATE TABLE chatrooms (
    chatroom_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 채팅방 번호 (기본키)
    tradebook_num NUMBER,
    seller_member_num NUMBER NOT NULL,                                       -- 판매자 회원 번호
    buyer_member_num NUMBER NOT NULL,                                        -- 구매자 회원 번호
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                          -- 채팅방 생성 시간
    left_member_nums VARCHAR2(500) DEFAULT NULL
);

CREATE TABLE messages (
    message_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 메시지 번호 (기본키)
    chatroom_num NUMBER NOT NULL,                                            -- 메시지가 속한 채팅방 번호
    sender_member_num NUMBER NOT NULL,                                       -- 메시지 보낸 사람 회원 번호
    message_content VARCHAR2(1000) NOT NULL,                                 -- 메시지 내용 (필수 입력)
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                             -- 메시지 전송 시간
    memssage_img VARCHAR2(200),
    is_read NUMBER DEFAULE 0
);

CREATE TABLE cart(
    cart_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    member_num NUMBER NOT NULL,
    newbook_num NUMBER NOT NULL,
    book_count NUMBER
);


-- 1. 도서 목록을 출간일순으로 정렬할 때
CREATE INDEX idx_newbook_publication_date ON newbook(newbook_publication_date);

-- 2. 결제 내역을 날짜순으로 정렬할 때
CREATE INDEX idx_payments_payment_date ON payments(payment_date);

-- 3. 메시지를 시간순으로 정렬할 때
CREATE INDEX idx_messages_sent_at ON messages(sent_at);

-- 4. 회원별 결제 내역 조회 시 빠른 검색
CREATE INDEX idx_payments_member_num ON payments(member_num);

-- 5. 회원별 게시글 조회 시 빠른 검색
CREATE INDEX idx_tradebook_member_num ON tradebook(member_num);
